MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: "/gdrive/Shared drives/REID/ReId-Survey-Paper/ReID-Survey/resnet50-19c8e357.pth"
  CENTER_LOSS: 'on'
  CENTER_FEAT_DIM: 2048
  NAME: 'resnet50_nl'
  WEIGHT_REGULARIZED_TRIPLET: 'on'
  GENERALIZED_MEAN_POOL: 'on'

INPUT:
  IMG_SIZE: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('market1501')

DATALOADER:
  PK_SAMPLER: 'on'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 160
  BASE_LR: 0.00035

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 60
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 64
  RE_RANKING: 'off'
  WEIGHT: "path"
  FEAT_NORM: 'on'
  EVALUATE_ONLY: 'off'
VISUALIZE :
  OPTION : "off"
  IMS_PER_BATCH : 256
  NEED_NEW_FEAT_EMBED : "off"
  INDEX : 0

OUTPUT_DIR: "./log/market1501/Experiment-AGW-baseline"


