MODEL:
    PRETRAIN_CHOICE: 'imagenet'
    # PRETRAIN_PATH: "/content/drive/Shared drives/REID/ReId-Survey-Paper/ReID-Survey/log/market1501/local-AGW-baseline/resnet50_nl_model_120.pth"
    PRETRAIN_PATH: '/home/thanit456/torch/weights/resnet50-19c8e357.pth'
    TRANSFER_MODE : 'off'
    BACKBONE: 'resnet50_nl'
    WEIGHT_REGULARIZED_TRIPLET: 'on'
    USE_COS: True
    USE_DROPOUT: False
    BASELINE: 
      POOL_TYPE: 'avg'
      COSINE_LOSS_TYPE: 'ArcFace'
      SCALING_FACTOR: 30.0
      MARGIN: 0.5
    # ? Lack of SEPNORM 
  
INPUT:
  IMG_SIZE: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  RE_MAX_RATIO: 0.2
  PADDING: 10

DATASETS:
  NAMES: ('market1501')

DATALOADER:
  PK_SAMPLER: 'on'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 3e-4
  MARGIN: 0.3
  MOMENTUM: 0.9

  # Center loss will always force using SGD optimizer
  CENTER_LOSS:
    USE: False
    LR: 0.5
    # ALPHA: 0.5
    WEIGHT: 0.0005
    NUM_FEATS: 2048

  WEIGHT_DECAY: 5e-4
  IMS_PER_BATCH: 64
  # IMS_PER_BATCH: 32


  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 100
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 64
  RE_RANKING: 'off'
  WEIGHT: "path"
  FEAT_NORM: 'on'
  EVALUATE_ONLY: 'off'
VISUALIZE :
  OPTION : "off"
  IMS_PER_BATCH : 256
  NEED_NEW_FEAT_EMBED : "off"
  INDEX : 0
  TOP_RANK : 10 
  RE_RANK : "off"
  CAM_OPTION : "none"
EMBEDDING_PROJECTOR:
  OPTION: "off"

OUTPUT_DIR: "./log/market1501/Experiment-AGW-baseline"

  
  